    version: '3.8'

    services:
      postgres.database:
        image: postgres:latest
        container_name: postgres.database
        restart: always
        environment:
          POSTGRES_PASSWORD: 2525
          POSTGRES_DB: Ticket
        ports:
          - "5432:5432"
        networks:
          - rede_ticket
        
      ticket:
        image: ${DOCKER_REGISTRY}ticket
        build:
          context: .
          dockerfile: Dockerfile
        container_name: tickets_api_container
        ports:
          - "8080:80"
        networks: 
          - rede_ticket
        depends_on: 
          - postgres.database
        
    networks:
        rede_ticket:
    
    volumes:
        postgres-data: